### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by spector012** [retkoussa/gsnw#2]
hello,
when i try to run to the tool i get the following error

`python3 gsnw.py PROTOB output.txt -silent
Traceback (most recent call last):
  File "/home/spector/bugbounty/tools/gsnw/gsnw.py", line 133, in <module>
    main()
  File "/home/spector/bugbounty/tools/gsnw/gsnw.py", line 116, in main
    matched_words = search_github(search_query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spector/bugbounty/tools/gsnw/gsnw.py", line 54, in search_github
    current_user = os.getlogin()
                   ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory`

please assist.

**Comment by retkoussa** [comment]
> hello, when i try to run to the tool i get the following error
> 
> `python3 gsnw.py PROTOB output.txt -silent Traceback (most recent call last): File "/home/spector/bugbounty/tools/gsnw/gsnw.py", line 133, in <module> main() File "/home/spector/bugbounty/tools/gsnw/gsnw.py", line 116, in main matched_words = search_github(search_query) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/spector/bugbounty/tools/gsnw/gsnw.py", line 54, in search_github current_user = os.getlogin() ^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory`
> 
> please assist.

Hi Spector, current this script supports Windows only - will work on linux support sometime down the future. No timeline for that as of now.
