### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by brightokine** [retkoussa/gsnw#3]
I don't seem to get any results with any keyword I use.
Always returns

---------------------------------
GSNW                                                                                                                                Find me on X (Twitter) @retkoussa
---------------------------------                                                                                                   Error: Message:                                                   
-------------------------                                         -------------------------

**Comment by momo1239** [comment]
Did you figure out a way to reesolve this? I'm having the same issue. I commented out the headless option and it seems to go to github.com with the search query without problems but something seems to be going wrong with the code and I always get Error: Message: empty as well.

**Comment by momo1239** [comment]
The issue is on this line

                EC.presence_of_all_elements_located((By.CLASS_NAME, "Link__StyledLink-sc-14289xe-0"))

**Comment by brightokine** [comment]
> Did you figure out a way to reesolve this? I'm having the same issue. I commented out the headless option and it seems to go to github.com with the search query without problems but something seems to be going wrong with the code and I always get Error: Message: empty as well. 

It's not resolved yet Sir.

**Comment by retkoussa** [comment]
Issue fixed.

Pull the repo again.

Also, reinstall requirements from from requirements.txt
